### PR TITLE
upgrade versions

### PR DESCRIPTION
**Pull request by xenowits**
* upgrade versions of `lighthouse`, `teku` and `geth` to their latest release.
* change network from `goerli` to `auto` in teku config.

Teku: https://github.com/ConsenSys/teku/releases
Lighthouse: https://github.com/sigp/lighthouse/releases/tag/v3.0.0
Geth: https://github.com/ethereum/go-ethereum/releases

### CODE REVIEW

**Comment by dB2510** [comment]
@xenowits update `teku-config.yml` to use `network: auto`

**Comment by xenowits** [comment]
Need to test with these versions locally before merging

**Comment by xenowits** [comment]
Need to upgrade charon to `v0.10.0` and geth to `v1.10.23`

**Comment by dB2510** [comment]
@xenowits I'll update charon version in separate PR. Need add and update some panels too. Raising PR shortly.

**Review by dB2510 — APPROVED** [review]

**Pull request merged**
